---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  recursive_additional_copy_path: .

platforms:
  - name: centos-7.2
    driver_config:
      image: rfhayashi/centos-ansible-chef

suites:
  - name: default
